repo_url: https://github.com/UnB-IHC/IHC_2025.2_Grupo10
repo_name: IHC_2025.2_Grupo10

site_url: https://pockets.github.io/IHC_2025.2_Grupo10/
site_name: WebAble

use_directory_urls: false

nav:
  - Início - WebAble: 'index.md'

  - Desenvolvimento Web:
      - Desenvolvimento: 'devWeb/non_text_content.md'

  - Design:
      - Design: 'design/design.md'

  - Geração de Conteúdo:
      - Conteúdo: 'geracaoConteudo/conteudo.md'

  - Gestão de Projetos:
      - Gestão de Projetos: 'gestaoProjeto/gestaoProjeto.md'

  - Heuristica de Nielsen:
      - Heurística de Nielsen: 'heuristica/heuristica.md'

  - Ferramentas:
      - Ferramentas de Acessibilidade: 'tools/ferramentas.md'

theme:
  name: material
  language: pt
  logo: imagens/logo.png
  favicon: imagens/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - navigation.instant: false
  palette:
    - scheme: default
      primary: amber
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Modo escuro
    - scheme: slate
      primary: amber
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Modo claro

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.blocks.caption
  - admonition

extra_css:
  #- stylesheets/extra.css
  - stylesheets/custom.css
  
extra_javascript:
  - https://cdn.jsdelivr.net/npm/chart.js
  - https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels
  - js/progresso.js
