
repo_url: https://github.com/UnB-IHC/IHC_2025.2_Grupo10
repo_name: IHC_2025.2_Grupo10

site_url: https://pockets.github.io/IHC_2025.2_Grupo10/
site_name: Projeto Grupo 10

use_directory_urls: False


nav:
  - Home: 'index.md'

  - Desenvolvimento Web:
    - Desenvolvimento: 'devWeb/non_text_content.md'

  - Design:
    - Design: 'design/design.md'
  
  - Geração de Conteúdo:
    - Conteúdo: 'geracaoConteudo/conteudo.md'

  - Gestão de Projetos:
    - Gestão de Projetos: 'gestaoProjeto/gestaoProjeto.md'

  - Ferramentas:
    - Ferramentas de Acessibilidade: 'tools/ferramentas.md'


theme:
  name: material
  language: pt
  logo: imagens/logo.png
  favicon: imagens/logo.png
  features:
    - navigation.instant
    - navigation.tabs   
    - navigation.top  
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: amber
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Modo escuro
    - scheme: slate
      primary: amber
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Modo claro


markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - admonition


extra_css:
  - stylesheets/extra.css
